
%dw 2.0
output application/java 
---
[{
    CASE_ID : 52,
    SOURCE : "velit,",
    CASE_TYPE : "consequat.",
    FIRST_NAME : "Alfreda",
    LAST_NAME : "Smithies",
    PHONE : "(753)-215-4962",
    EMAIL : "Alane.Smorthit@gmail.com",
    DATE_OF_BIRTH : |2017-07-13|,
    NATIONAL_ID : "2086ca0d3b8a4db2809",
    NATIONAL_ID_TYPE : "exercitationem",
    STREET_ADDRESS : "voluptate",
    CITY : "Cordoba",
    STATE : "esse",
    POSTAL : "sint",
    COUNTRY : "Costa Rica",
    CREATE_DATE : |2002-11-27|,
    UPDATE_DATE : |2011-05-08|,
    CREATE_BY : "cupidatat",
    UPDATE_BY : "dolor",
  },
{
    CASE_ID : 31,
    SOURCE : "culpa",
    CASE_TYPE : "minima",
    FIRST_NAME : "Bud",
    LAST_NAME : "Smithers",
    PHONE : "(447)-644-6944",
    EMAIL : "Almeda.Aliberti@gmail.com",
    DATE_OF_BIRTH : |2004-01-12|,
    NATIONAL_ID : "f34714e2aa9f4cb8839",
    NATIONAL_ID_TYPE : "nisi",
    STREET_ADDRESS : "laboriosam,",
    CITY : "Chicago",
    STATE : "adipiscing",
    POSTAL : "et",
    COUNTRY : "Bahamas",
    CREATE_DATE : |2006-10-16|,
    UPDATE_DATE : |2001-11-18|,
    CREATE_BY : "eum",
    UPDATE_BY : "quia",
  }]
